sudo: false
language: generic
matrix:
    include:
        - os: linux

cache:
    directories:
        - /tmp/texlive
        - $HOME/.texlive

before_install: 
- bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk thesis-sample.tex

